version: "3"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  frontend:
    build: ./client
    ports:
      - "3001:80"
    depends_on:
      - backend
